import {
  mdiPlay,
  mdiPause,
  mdiSkipPrevious,
  mdiSkipNext,
  mdiTableOfContents,
  mdiArrowDown,
  mdiArrowUp,
  mdiEye,
  mdiEyeOff,
  mdiExitToApp,
  mdiHelp,
  mdiAccountSettings,
  mdiAlertCircle,
  mdiCheckCircle,
  mdiFileUpload,
  mdiFileImage,
  mdiDelete,
  mdiFile,
  mdiCheckAll,
  mdiVolumeMute,
  mdiVolumeHigh,
  mdiVolumeMedium,
  mdiMovie,
  mdiPictureInPictureBottomRight,
  mdiFullscreen,
  mdiShuffle,
  mdiRepeat,
  mdiRepeatOnce
} from '@mdi/js';

export const iconsList = {
  arrowDown: mdiArrowDown,
  arrowUp: mdiArrowUp,
  play: mdiPlay,
  pause: mdiPause,
  prev: mdiSkipPrevious,
  next: mdiSkipNext,
  playlist: mdiTableOfContents,
  eyeClosed: mdiEyeOff,
  eyeOpened: mdiEye,
  exitToApp: mdiExitToApp,
  help: mdiHelp,
  manageAccount: mdiAccountSettings,
  error: mdiAlertCircle,
  success: mdiCheckCircle,
  checkTick: mdiCheckAll,
  upload: mdiFileUpload,
  image: mdiFileImage,
  media: mdiFile,
  delete: mdiDelete,
  mute: mdiVolumeMute,
  volumeHigh: mdiVolumeHigh,
  volumeMedium: mdiVolumeMedium,
  movie: mdiMovie,
  PIPRight: mdiPictureInPictureBottomRight,
  fullScreen: mdiFullscreen,
  shuffle: mdiShuffle,
  repeat: mdiRepeat,
  repeatOnce: mdiRepeatOnce
};